// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";



const connectionString = `${process.env.DATABASE_URL}`
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: env('DATABASE_URL'),
  },
});


// prisma.config.js

import { PrismaClient } from './generated/prisma/client.js';
import { PrismaMariaDb } from '@prisma/adapter-mariadb';
import { withAccelerate } from '@prisma/extension-accelerate'

const mysql = new PrismaMariaDb({
  host: process.env.Host || 'localhost',
  user: process.env.User || 'user',
  password: process.env.Password || 'password',
  database: process.env.Database || 'mydb',
  port: 3306,
});

const prisma = new PrismaClient({ adapter : mysql })

export { prisma }
